@startuml lab2_1

(*) --> ===A1===

--> "Переглянути інформаційну сторінку"
--> ===A2===

===A1=== --> "Пошук рейсів"
--> "Ввести пункт призначення"
--> "Вибрати дату"
--> "Обрати клас місця"
--> ===A2===

===A1=== --> "Переглянути доступні рейси"
if "" then
--> "Вибрати рейс"
--> ===B1===
===B1=== --> "Обрати місце в салоні"
--> ===B2===
===B1=== --> "Додати додаткові послуги"
--> ===B2===
--> "Продовжити до оплати"
--> ===A2===

else
--> "Перевірити статус бронювання"
--> ===C1===
===C1=== --> "Відмінене"
--> ===C2===
===C1=== --> "Оплачене"
--> ===C2===
===C1=== --> "Не оплачене"
--> ===C2===
--> ===A2===

--> (*)

@enduml

