@startuml lab2_2

(*) --> ===A1===
--> "Перевірити запит на допоміжну інформацію"
--> ===A2===

===A1=== --> "Обробка запиту на перегляд доступних рейсів"
--> ===A3===

===A3=== --> "Фільтрація рейсів за параметрами"
if "" then
--> "Відправлення списку відфільтрованих рейсів"
else
--> "Відправлення повідомлення про помилку"
--> ===A2===

===A3=== --> "Запит на зміну деталей бронювання"
--> "Валідація даних бронювання"
if "" then
--> "Відправлення підтвердження зміни"
else
--> "Відправлення повідомлення про помилку"
--> ===A2===

===A1=== --> "Запит на створення нового бронювання"
--> "Валідація даних нового бронювання"
if "" then
--> "Відправлення підтвердження створення бронювання"
else
--> "Відправлення повідомлення про помилку"
--> ===A2===
--> (*)

@enduml
