@startuml lab3_1

actor "Клієнт" as CL

CL -> "Сервер" : Запит перегляду сторінки допомоги
activate "Сервер"
"Сервер" --> CL : Повернення сторінки з допомогою
deactivate "Сервер"

CL -> "Сервер" : Запит доступних рейсів
activate "Сервер"
"Сервер" --> CL : Показ доступних рейсів
deactivate "Сервер"

CL -> "Сервер" : Запит перегляду деталей рейсу
activate "Сервер"
"Сервер" --> CL : Повернення деталей рейсу
deactivate "Сервер"

CL -> "Сервер" : Бронювання рейсу
activate "Сервер"
"Сервер" --> CL : Підтвердження бронювання
deactivate "Сервер"

CL -> "Сервер" : Запит сторінки купівлі авіаквитка
activate "Сервер"
"Сервер" --> CL : Повернення сторінки для оплати
deactivate "Сервер"

CL -> "Сервер" : Купівля авіаквитка
activate "Сервер"
"Сервер" --> CL : Підтвердження купівлі та надсилання електронного квитка
deactivate "Сервер"

@enduml
